### PR TITLE
Update package to 0.7/1.0

### PR DESCRIPTION
**Pull request by timholy**
All of the changes (including moving comments or blank lines out from between the docstring and the function definition) are needed to fix deprecation warnings.

### CODE REVIEW

**Comment by peterkovesi** [comment]
Tim,  Thank you very much for all your work here.  I had been meaning to update things for a while but I have fallen out of using Julia lately (version fatigue!) and had been neglecting my packages.  Thank you once again!

**Comment by timholy** [comment]
Oh, I understand. I've spent a couple weeks a year (at least) updating to new Julia versions. Hopefully now we can all quit doing that, at least for the next several years!

**Comment by timholy** [comment]
Would you be willing to tag a new release?

**Comment by peterkovesi** [comment]
v0.3.0 tagged and merged into METADATA

**Pull request merged**
